### ISSUE TITLE
I need your paper

### ISSUE THREAD

**Issue by luckyboyjeff** [nbvanting/thesis#1]
Thank you very much for providing the code, which is so detailed and accurate. This makes me eager to read your paper "ELECTRICITY CONSUMPTION FORECAST OF RESIDENTIAL HOUSING USING DEEP NEURAL NETWORKS". I cannot find the paper on the Internet. I hope you can send it to me. Thank you

**Comment by nbvanting** [comment]
Unfortunately, I am not yet able to provide a copy of the thesis because of sensitive data and contents.
